artifact_location: /home/ahmedcr7/Programming/Python/AI/computer vision/Object_detection/YOLO/runs/mlflow/0
creation_time: 1732722760281
experiment_id: '0'
last_update_time: 1732722760281
lifecycle_stage: active
name: Default
