artifact_location: /home/ahmedcr7/Programming/Python/AI/computer vision/Object_detection/YOLO/runs/mlflow/518425210066571296
creation_time: 1732722760294
experiment_id: '518425210066571296'
last_update_time: 1732722760294
lifecycle_stage: active
name: /Shared/Ultralytics
